title: JesData — Tutoriales
description: Portal de tutoriales técnicos sobre Ingeniería de Datos y Microsoft Fabric
theme: just-the-docs

url: https://jes-data.github.io

nav_enabled: false
search_enabled: false
color_scheme: light

plugins:
  - jekyll-seo-tag
